@startuml crearPrograma

skinparam linetype polyline

state crearPrograma as "crearPrograma()" {

    state " " as SolicitandoDatos
    state " " as CreandoPrograma

    [*] -[#green]-> SolicitandoDatos 
    note on link
    <b>Administrador</b> solicita crear programa nuevo
    end note    
    
    SolicitandoDatos -[#green]-> CreandoPrograma
    note on link
    <b>Sistema</b> solicita datos mínimos del programa
    • Nombre del programa (obligatorio)
    • Permite solicitar crear programa
    • Permite solicitar cancelar creación
    end note
    
    CreandoPrograma -[#green]-> [*]
    note on link
    <b>Administrador</b> proporciona datos mínimos
    <b>Sistema</b> crea programa y transfiere a edición
    end note
}

crearPrograma -[#green]-> PROGRAMA_ABIERTO
note on link
editarPrograma(programaNuevo)
end note

crearPrograma -[#blue]-> PROGRAMAS_ABIERTO
note on link
cancelar creación
end note

@enduml