@startsalt solicitarConfirmacion-wireframe
{
    <b>CONFIRMACIÓN</b>
    ===
    {
        "¿Está seguro de que desea realizar esta acción?"
        --
        {[Aceptar] | [Cancelar]}
    }
}
@endsalt