@startuml
[*] --> NoEncontrado : int i=0

NoEncontrado --> NoEncontrado : (i<t.length && t[i]!=k) / i++

NoEncontrado --> [*] : (i<t.length && t[i]==k) / A()
NoEncontrado --> [*] : (i>=t.length) / B()
@enduml