' Autor: Prof. Luis Fernandez

hide circle
hide stereotype

package disciplinas {
class Disciplina
class DisciplinaRequisitos as "Disciplina de\nRequisitos"
}

package actividades {
class Actividad
class ActividadRequisitos as "Actividad de\nRequisitos"
class EncontrarActoresCasosUso as "Encontrar Actores\ny Casos de Uso"
class PriorizarCasosUso as "Priorizar\nCasos de Uso"
class DetallarCasoUso as "Detallar\nCaso de Uso"
class EstructurarModeloCasosUso as "Estructurar Modelo\nde Casos de Uso"
class PrototiparInterfaz as "Prototipar\nInterfaz"
}

package equipo {
class Miembro
class Rol
class RolRequisitos as "Rol de\nRequisitos"
class AnalistaSistemas as "Analista de\nSistemas"
class EspecificadorCasosUso as "Especificador de\nCasos de Uso"
class Arquitecto
class DiseñadorInterfaz as "Diseñador de\nInterfaz"
}

Disciplina *--> Actividad

Disciplina <|-- DisciplinaRequisitos
DisciplinaRequisitos *--> "*" ActividadRequisitos

Actividad <|-- ActividadRequisitos
ActividadRequisitos *--> Miembro

Miembro *--> Rol

Rol <|-- RolRequisitos

ActividadRequisitos <|-- EncontrarActoresCasosUso
EncontrarActoresCasosUso --> AnalistaSistemas
EncontrarActoresCasosUso  --> PriorizarCasosUso :siguiente

ActividadRequisitos <|-- PriorizarCasosUso
PriorizarCasosUso --> Arquitecto
PriorizarCasosUso  --> DetallarCasoUso :siguiente

ActividadRequisitos <|-- DetallarCasoUso
DetallarCasoUso --> EspecificadorCasosUso
DetallarCasoUso  --> EstructurarModeloCasosUso :siguiente
DetallarCasoUso  --> PrototiparInterfaz :siguiente

ActividadRequisitos <|-- EstructurarModeloCasosUso
EstructurarModeloCasosUso --> AnalistaSistemas

ActividadRequisitos <|-- PrototiparInterfaz
PrototiparInterfaz --> DiseñadorInterfaz

RolRequisitos <|-- AnalistaSistemas
RolRequisitos <|-- EspecificadorCasosUso
RolRequisitos <|-- Arquitecto
RolRequisitos <|-- DiseñadorInterfaz
