' Autor: Prof. Luis Fernandez

hide circle
hide stereotype

package fases {
class Fase
class Inicio as "Fase de\nInicio"
class Elaboracion as "Fase de\nElaboración"
class Construccion as "Fase de\nConstrucción"
class Transicion as "Fase de\nTransición"
}

class Iteracion

package disciplinas {
class Disciplina
class DisciplinaRequisitos as "Disciplina de\nRequisitos"
class DisciplinaAnalisis as "Disciplina de\nAnálisis"
class DisciplinaDiseño as "Disciplina de\nDiseño"
class DisciplinaImplementacion as "Disciplina de\nImplementación"
class DisciplinaPruebas as "Disciplina de\nPruebas"
}

package actividades {
class Actividad
class ActividadRequisitos as "Actividad de\nRequisitos"
class ActividadAnalisis as "Actividad de\nAnálisis"
class ActividadDiseño as "Actividad de\nDiseño"
class ActividadImplementacion as "Actividad de\nImplementación"
class ActividadPruebas as "Actividad de\nPruebas"
}

package equipo {
class Miembro
class Rol
class RolRequisitos as "Rol de\nRequisitos"
class RolAnalisis as "Rol de\nAnálisis"
class RolDiseño as "Rol de\nDiseño"
class RolImplementacion as "Rol de\nImplementación"
class RolPruebas as "Rol de\nPruebas"
}

Fase *-r-> Iteracion
Fase <|-- Inicio
Inicio --> Elaboracion : siguiente
Fase <|-- Elaboracion
Elaboracion  --> Construccion :siguiente
Fase <|-- Construccion
Construccion  -->  Transicion :siguiente
Fase <|-- Transicion

Iteracion *--> Disciplina
Iteracion --> Iteracion :siguiente

Disciplina *--> Actividad
Disciplina <|-- DisciplinaRequisitos
DisciplinaRequisitos *--> "*" ActividadRequisitos
DisciplinaRequisitos --> DisciplinaAnalisis :siguiente
Disciplina <|-- DisciplinaAnalisis
DisciplinaAnalisis *--> "*" ActividadAnalisis
DisciplinaAnalisis --> DisciplinaDiseño :siguiente
Disciplina <|-- DisciplinaDiseño
DisciplinaDiseño *--> "*" ActividadDiseño
DisciplinaDiseño --> DisciplinaImplementacion :siguiente
Disciplina <|-- DisciplinaImplementacion
DisciplinaImplementacion *--> "*" ActividadImplementacion
DisciplinaImplementacion --> DisciplinaPruebas :siguiente
Disciplina <|-- DisciplinaPruebas
DisciplinaPruebas *--> "*" ActividadPruebas

Actividad <|-- ActividadRequisitos
ActividadRequisitos --> ActividadAnalisis :siguiente
Actividad <|-- ActividadAnalisis
ActividadAnalisis --> ActividadDiseño :siguiente
Actividad <|-- ActividadDiseño
ActividadDiseño --> ActividadImplementacion :siguiente
Actividad <|-- ActividadImplementacion
ActividadImplementacion --> ActividadPruebas :siguiente
Actividad <|-- ActividadPruebas

Actividad --> Miembro
Miembro *--> Rol
Rol <|-- RolRequisitos
Rol <|-- RolAnalisis
Rol <|-- RolDiseño
Rol <|-- RolImplementacion
Rol <|-- RolPruebas

ActividadRequisitos --> "*" RolRequisitos
ActividadAnalisis --> "*" RolAnalisis
ActividadDiseño --> "*" RolDiseño
ActividadImplementacion --> "*" RolImplementacion
ActividadPruebas --> "*" RolPruebas
