' Autor: Prof. Luis Fernandez

hide circle
hide stereotype

class Rol as "Rol"
class RolRequisitos as "Rol de\nRequisitos"
class RolAnalisis as "Rol de\nAnálisis"
class RolDiseño as "Rol de\nDiseño"
class RolImplementacion as "Rol de\nImplementación"
class RolPruebas as "Rol de\nPruebas"

class AnalistaSistemas as "Analista de\nSistemas"
class EspecificadorCasosUso as "Especificador de\nCasos de Uso"
class DiseñadorInterfaz as "Diseñador de\nInterfaz"
class IngenieuroCasosUso as "Ingeniero de\nCasos de Uso"
class Arquitecto
class IngenieroComponentes as "Ingeniero de\nComponentes"
class IntegradorSistemas as "Integrador de\nSistemas"
class IngenieuroPruebas as "Ingeniero de\nPruebas"
class ProbadorSistemas as "Probador de\nSistemas"
class ProbadorIntegracion as "Probador de\nIntegración"

Rol <|-- RolRequisitos
Rol <|-- RolAnalisis
Rol <|-- RolDiseño
Rol <|-- RolImplementacion
Rol <|-- RolPruebas

RolRequisitos <|-- AnalistaSistemas
RolRequisitos <|-- EspecificadorCasosUso
RolRequisitos <|-- Arquitecto
RolRequisitos <|-- DiseñadorInterfaz

RolAnalisis <|-- Arquitecto
RolAnalisis <|-- IngenieuroCasosUso
RolAnalisis <|-- IngenieroComponentes

RolImplementacion <|-- Arquitecto
RolImplementacion <|-- IntegradorSistemas
RolImplementacion <|-- IngenieroComponentes

RolPruebas <|-- IngenieuroPruebas
RolPruebas <|-- ProbadorSistemas
RolPruebas <|-- ProbadorIntegracion
RolPruebas <|-- IngenieroComponentes

RolDiseño <|-- Arquitecto
RolDiseño <|-- IngenieuroCasosUso
RolDiseño <|-- IngenieroComponentes