' Autor: Prof. Luis Fernandez

hide circle
hide stereotype

class Role
class RequirementRole as "Requirement\nRole" <<requirement>>
class AnalysisRole as "Analysis\nRole" <<analysis>>
class DesignRole as "Design\nRole" <<design>>
class ImplementRole as "Implementation\nRole" <<implementation>>
class TestRole as "Test\nRole" <<test>>

class SystemsAnalyst as "Systems\nAnalyst" <<requirement>>
class UseCaseSpecifier as "Use Case\nSpecifier" <<requirement>>
class InterfaceDesigner as "Interface\nDesigner" <<requirement>>
class UseCaseEngineer as "Use Case\nEngineer" <<several>>
class Architect <<several>>
class ComponentEngineer as "Component\nEngineer" <<several>>
class SystemIntegrator as "System\nIntegrator" <<implementation>>
class TestEngineer as "Test\nEngineer" <<test>>
class SystemTester as "System\nEngineer" <<test>>
class IntegrationTester as "Integration\nTester" <<test>>

Role <|-- RequirementRole
Role <|-- AnalysisRole
Role <|-- DesignRole
Role <|-- ImplementRole
Role <|-- TestRole

RequirementRole <|-- SystemsAnalyst
RequirementRole <|-- UseCaseSpecifier
RequirementRole <|-- Architect
RequirementRole <|-- InterfaceDesigner

AnalysisRole <|-- Architect
AnalysisRole <|-- UseCaseEngineer
AnalysisRole <|-- ComponentEngineer

ImplementRole <|-- Architect
ImplementRole <|-- SystemIntegrator
ImplementRole <|-- ComponentEngineer

TestRole <|-- TestEngineer
TestRole <|-- SystemTester
TestRole <|-- IntegrationTester
TestRole <|-- ComponentEngineer

DesignRole <|-- Architect
DesignRole <|-- UseCaseEngineer
DesignRole <|-- ComponentEngineer