@startuml

Jugador "1" -- "0..*" Objeto: posee >
Jugador "1" -- "0..*" Mision: realiza >
Jugador "1" -- "0..*" Reliquia: controla >

Personaje <|-- Enemigo

Objeto <|-- Arma
Objeto <|-- Armadura
Objeto <|-- Ingrediente

Ubicacion "1" -- "0..*" Personaje: contiene >
Ubicacion "1" -- "0..*" Enemigo: habita >
Ubicacion "1" -- "0..*" Objeto: contiene >

BestiaDivina "1" -- "1" Enemigo: tiene jefe >
BestiaDivina "1" -- "1" Ubicacion: situada en >

Jugador "1" -- "1" SistemaCocina: usa >
SistemaCocina "1" -- "0..*" Ingrediente: utiliza >

@enduml