@startuml editarAula

skinparam linetype polyline

state editarAula as "editarAula()" {

    state " " as EditandoDatos
    state " " as GuardandoDatos 

    [*] -[#green]-> EditandoDatos 
    note on link
    <b>Administrador</b> solicita editar aula
    end note    
    
    EditandoDatos -[#green]-> GuardandoDatos
    note on link
    <b>Sistema</b> presenta datos de edición
    • Código, nombre del aula
    • Edificio asociado, capacidad
    • Tipo de aula, recursos
    • Observaciones del aula
    
    <b>Sistema</b> permite solicitar:
    • modificar campos
    • guardar aula
    • cancelar edición
    end note
    
    GuardandoDatos -[#green]-> EditandoDatos
    note on link
    <b>Administrador</b> solicita modificar campos
    end note
    
    GuardandoDatos -[#green]-> [*]
    note on link
    <b>Administrador</b> solicita guardar y salir
    end note

    GuardandoDatos -[#red]-> [*]
    note on link
    <b>Administrador</b> solicita cancelar edición
    end note

}

editarAula -[#green]-> AULAS_ABIERTO
note on link
abrirAulas()
end note

editarAula -[#red]-> AULAS_ABIERTO
note on link
cancelar edición
end note

@enduml