@startsalt abrirAulas-wireframe
{ 
<b>GESTIÓN DE AULAS</b>  
===
{+  ID | NOMBRE | CAPACIDAD | EDIFICIO | ACCIÓN
  --|--|--|--|--
  001 | Aula 101 | 30 | Edificio Principal | [Editar]
  002 | Aula 102 | 25 | Edificio Principal | [Editar]
  003 | Lab 201 | 20 | Edificio de Laboratorios | [Editar]
  004 | Aula Magna | 100 | Edificio Principal | [Editar]
  }
  ~~
  {<b>BUSCAR:</b> [                                       ] | [Filtrar]}
  ~~
  {[Crear nuevo] | [Borrar seleccionado] | [Salir]}
}

@endsalt