@startsalt eliminarCurso-wireframe
{
    <b>ELIMINAR CURSO ACADÉMICO</b>
    ===
    {
        <b>¿Está seguro de eliminar este curso?</b>
        --
        {
            {<b>Código:</b> | CUR-001
            <b>Nombre:</b> | Cálculo Diferencial}
            {<b>Descripción:</b> |
            {
                Curso de matemática fundamental que introduce
                conceptos de límites, derivadas y aplicaciones
                del cálculo diferencial
            }}
            {<b>Créditos:</b> | 4
            <b>Horas teóricas/semana:</b> | 3
            <b>Horas prácticas/semana:</b> | 2
            <b>Programa académico:</b> | Ingeniería Industrial y de Sistemas}
            --
            <b>⚠️ ADVERTENCIA: Esta acción es irreversible</b>
            <i>El curso y toda su información asociada serán eliminados permanentemente</i>
        }

        ~~

        {[Confirmar eliminación] | [Cancelar]}
    }
}
@endsalt